version: "3.9"

services:
  auth-service:
    build: ./auth-service
    ports:
      - "8001:8000"
    environment:
      - DATABASE_URL=sqlite:////app/db/auth.db
    volumes:
      - auth_db:/app/db

  inventory-service:
    build: ./inventory-service
    ports:
      - "8002:8000"
    environment:
      - DATABASE_URL=sqlite:////app/db/inventory.db
    volumes:
      - inventory_db:/app/db

  rental-service:
    build: ./rental-service
    ports:
      - "8003:8000"
    environment:
      - DATABASE_URL=sqlite:////app/db/rental.db
    volumes:
      - rental_db:/app/db

volumes:
  auth_db:
  inventory_db:
  rental_db:
