services:
  # -------------------------
  # AUTH SERVICE
  # -------------------------
  - name: bike4you-auth
    type: web
    env: docker
    rootDir: auth-service
    plan: free
    region: frankfurt
    envVars:
      - key: DATABASE_URL
        value: sqlite:////data/auth.db
      - key: SECRET_KEY
        value: SUPER_SECRET_KEY_CHANGE_ME
    disks:
      - name: authdisk
        mountPath: /data
        sizeGB: 1

  # -------------------------
  # INVENTORY SERVICE
  # -------------------------
  - name: bike4you-inventory
    type: web
    env: docker
    rootDir: inventory-service
    plan: free
    region: frankfurt
    envVars:
      - key: DATABASE_URL
        value: sqlite:////data/inventory.db
      - key: SECRET_KEY
        value: SUPER_SECRET_KEY_CHANGE_ME
    disks:
      - name: invdisk
        mountPath: /data
        sizeGB: 1

  # -------------------------
  # RENTAL SERVICE
  # -------------------------
  - name: bike4you-rental
    type: web
    env: docker
    rootDir: rental-service
    plan: free
    region: frankfurt
    envVars:
      - key: DATABASE_URL
        value: sqlite:////data/rental.db
      - key: INVENTORY_URL
        value: https://bike4you-inventory.onrender.com
      - key: SECRET_KEY
        value: SUPER_SECRET_KEY_CHANGE_ME
    disks:
      - name: rentaldisk
        mountPath: /data
        sizeGB: 1
