services:
  # =========================
  # AUTH SERVICE
  # =========================
  - name: bike4you-auth
    type: web
    env: docker
    rootDir: auth-service
    plan: free
    region: oregon
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: bike4you-db
          property: connectionString
      - key: SECRET_KEY
        value: SUPER_SECRET_KEY_CHANGE_ME

  # =========================
  # INVENTORY SERVICE
  # =========================
  - name: bike4you-inventory
    type: web
    env: docker
    rootDir: inventory-service
    plan: free
    region: oregon
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: bike4you-db
          property: connectionString
      - key: SECRET_KEY
        value: SUPER_SECRET_KEY_CHANGE_ME

  # =========================
  # RENTAL SERVICE
  # =========================
  - name: bike4you-rental
    type: web
    env: docker
    rootDir: rental-service
    plan: free
    region: oregon
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: bike4you-db
          property: connectionString
      - key: INVENTORY_URL
        value: https://bike4you-inventory.onrender.com
      - key: SECRET_KEY
        value: SUPER_SECRET_KEY_CHANGE_ME
